books = []
books.append("c")
print(books)
print("Now the top books is = ",books[0])
books.append("c++")
print(books)
print("Now the top books is = ",books[+1])
books.append("java")
print(books)
print("Now the top books is = ",books[+2])
books.pop()
print(books)
print("Now the top books is = ",books[-1])
books.pop()
print(books)
print("Now the top books is = ",books[-1])
books.pop()
if not books:
    print("No books left")